import { ICustomer } from "@/app/types/customer";

export const customers: ICustomer[] = [
	{
		id: 1,
		name: "John",
		secondName: "Alexis",
		lastName: "Doe",
		secondLastName: "Zhu",
		email: "john@mail.com",
		phoneNumber: "123456789",
		address: "Calle 123",
	},
	{
		id: 2,
		name: "Pablo",
		secondName: "Martin",
		lastName: "Villacres",
		secondLastName: "Morales",
		email: "john@mail.com",
		phoneNumber: "123456789",
		address: "Calle 123",
	},
	{
		id: 3,
		name: "Jair",
		secondName: "Alexis",
		lastName: "Mera",
		secondLastName: "Toasa",
		email: "john@mail.com",
		phoneNumber: "123456789",
		address: "Calle 123",
	},
	{
		id: 4,
		name: "Erick",
		secondName: "Daniel",
		lastName: "Zhu",
		secondLastName: "Ordoñez",
		email: "john@mail.com",
		phoneNumber: "123456789",
		address: "Calle 123",
	},
	{
		id: 5,
		name: "John",
		secondName: "Alexis",
		lastName: "Doe",
		secondLastName: "Zhu",
		email: "john@mail.com",
		phoneNumber: "123456789",
		address: "Calle 123",
	},
];
